### ISSUE TITLE
Indigo

### ISSUE THREAD

**Issue by wjwwood** [ethz-asl/map_msgs#4]
Who is willing to maintain and release this for Indigo?

Currently it is blocking the release of `rviz`.

@stephanemagnenat?

**Comment by wjwwood** [comment]
I am going to release the current version into indigo as unmaintained, but if it will remain unmaintained, I would consider removing it as a direct dependency for rviz.

**Comment by wjwwood** [comment]
Released into Indigo: https://github.com/ros/rosdistro/pull/3232

**Comment by stephanemagnenat** [comment]
Hi William,

I am open about what to do with this package. Currently our work on mapping has shifted to a more database-oriented system (https://github.com/ethz-asl/map_manager_api) as after talking to many people at Willow and here I realised that stream-based API is not well suited for the mapping problems we approach. Therefore, I consider the REP I was working on as outdated compared to the map manager API linked above. We now have a master student who will write a prototype of this API, we will of course keep the ROS community informed of any significant progresses.

So, what would be more convenient for you to do with this map_msgs package for now?

**Comment by wjwwood** [comment]
Seeing as that maintenance on this package will be negligible, I think it is best to leave it as it is. I was thinking we could remove `map_msgs` and the plugin that uses them from the default rviz plugin and make it a separate plugin in a separate package would be cleaner in that it minimizes rviz's dependencies. However, I'm not sure it's worth all the effort. I believe this is used by the navigation stack to visualize costmaps, so it would need to be in desktop-full anyways.

@stephanemagnenat would you be willing to maintain this for Indigo, with the understanding that the maintenance should basically be zero and that I will help you with any of the tasks since it is a dependency of rviz?

**Comment by stephanemagnenat** [comment]
@wjwwood I would say, but knowing that I have not upgraded out of groovy yet, it is maybe not a so serious statement from me.

**Comment by wjwwood** [comment]
That's fine, all I really need help with is addressing incoming issues, not necessarily fixing and closing them, just keeping the lights on for this issue tracker.

I'll leave you in the `package.xml` as a maintainer.

I can do releases for Indigo and fix any indigo bugs (Shouldn't be any).
