### ISSUE TITLE
Release into ROS Jade

### ISSUE THREAD

**Issue by mikeferguson** [ethz-asl/map_msgs#5]
Please release this package into ROS Jade as it is a blocking dependency of the navigation stack

**Comment by mikeferguson** [comment]
Actually, @stephanemagnenat how would you feel about upstreaming this package into the ros-planning organization for Jade and above?

In particular, there has been discussion of moving move_base_msgs out of the navigation repo so that message-only users can get messages easier. I would propose we create a navigation-msgs repo with move_base_msgs and map_msgs packages in it.

**Comment by stephanemagnenat** [comment]
I am not involved with ROS these days any more (but will be maybe in the future), so it is perfectly fine for me to upstream this package. How should I proceed practically?

**Comment by mikeferguson** [comment]
@stephanemagnenat I can take care of creating the upstream repository, just wanted to have your blessing before doing so. Once I have, I will probably create a PR to update the README of this repo letting people know that for Jade+ they should look at the new repo.

**Comment by jack-oquin** [comment]
+1 Seems like a good plan. 

Thanks, Stephan and Mike, for keeping things going.

**Comment by stephanemagnenat** [comment]
you have my blessing :-)

**Comment by mikeferguson** [comment]
Repo is here: https://github.com/ros-planning/navigation_msgs

Release is here: https://github.com/ros/rosdistro/pull/7536

**Comment by mikeferguson** [comment]
PR to add README with new location is here: https://github.com/ethz-asl/map_msgs/pull/6
